package com.example.demo.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

@Entity
@Table(name = "reports")
public class Report {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Report type is required")
    @Column(nullable = false)
    private String reportType;

    @NotNull(message = "Generated date is required")
    @Column(nullable = false)
    private LocalDateTime generatedDate;

    @NotBlank(message = "Generated by is required")
    @Column(nullable = false)
    private String generatedBy;

    @Size(max = 500, message = "Summary must not exceed 500 characters")
    @Column(length = 500)
    private String summary;

    public Report() {}

    public Report(String reportType, String generatedBy, String summary) {
        this.reportType = reportType.trim();
        this.generatedDate = LocalDateTime.now(); // auto-set on creation
        this.generatedBy = generatedBy.trim();
        this.summary = (summary != null) ? summary.trim() : null;
    }

    // Getters
    public Long getId() { return id; }
    public String getReportType() { return reportType; }
    public LocalDateTime getGeneratedDate() { return generatedDate; }
    public String getGeneratedBy() { return generatedBy; }
    public String getSummary() { return summary; }

    // Setters
    public void setId(Long id) { this.id = id; }
    public void setReportType(String reportType) { this.reportType = (reportType != null) ? reportType.trim() : null; }
    public void setGeneratedDate(LocalDateTime generatedDate) { this.generatedDate = generatedDate; }
    public void setGeneratedBy(String generatedBy) { this.generatedBy = (generatedBy != null) ? generatedBy.trim() : null; }
    public void setSummary(String summary) { this.summary = (summary != null) ? summary.trim() : null; }

    @Override
    public String toString() {
        return "Report{id=" + id +
                ", reportType='" + reportType + '\'' +
                ", generatedDate=" + generatedDate +
                ", generatedBy='" + generatedBy + '\'' +
                ", summary='" + summary + '\'' +
                '}';
    }
}